name: CI-CD

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Image
        run: docker build -t node-app .

      - name: Tag Image
        run: docker tag node-app:latest public.ecr.aws/i6g2k9g5/test-node-app:latest

      - name: Push Image
        run: docker push public.ecr.aws/i6g2k9g5/test-node-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            
            script: |
                aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i6g2k9g5/test-node-app:latest
                docker pull public.ecr.aws/i6g2k9g5/test-node-app:latest
                docker stop node-app || true
                docker rm node-app || true
                docker run -d --name node-app -p 8000:8000 public.ecr.aws/i6g2k9g5/test-node-app:latest
    